spring:
  application:
    name: SkillForge

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/original_skillforge
    username: moderador
    password: skillforge25
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect